services:
  api:
    build:
      context: .
      dockerfile: DataCrawler.API/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - .:/app/data
    depends_on:
      - worker

  worker:
    build:
      context: .
      dockerfile: DataCrawler.Worker/Dockerfile
    volumes:
      - .:/app/data